services:
  - type: web
    name: medical-image-detector
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: models
      mountPath: /opt/render/project/src/models
      sizeGB: 10
